<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBn03xzw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBn03xzw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBn03xzw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBn03xzw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBn03xzw\appProdProjectContainer([
    'container.build_hash' => 'Bn03xzw',
    'container.build_id' => '854d1f5f',
    'container.build_time' => 1693909143,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBn03xzw');
