<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7iisrje\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7iisrje/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7iisrje.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7iisrje\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7iisrje\appDevDebugProjectContainer([
    'container.build_hash' => '7iisrje',
    'container.build_id' => 'c7f38820',
    'container.build_time' => 1693917066,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7iisrje');
